
name: NuScenes
dataset_name: NuScenes
dataset_root: data/nuscenes
desc: inI_predI
save_dir: results/nuScenes/

# splits
train_split: parametrizing
val_split: verifying
test_split: val

# inputs
inputs: ["intensities"] # ["x"] would be only ones

# optimization
training:
  max_epochs: 200
  batch_size: 16
  val_interval: 5

optimizer: torch.optim.AdamW
optimizer_params:
  lr: 0.001

# network
network:
  framework: torchsparse
  backbone: MinkUNet34
  backbone_params: 
    quantization_params:
      voxel_size: 0.1
  decoder: InterpNet
  decoder_params:
    radius: 1.0
    out_channels: 2 # 1 for reconstruction, 1 for intensity
    intensity_loss: true
    radius_search: true
  latent_size: 128

# losses
loss:
  recons_loss_lambda: 1
  intensity_loss_lambda: 1

# misc
device: cuda
num_device: 1
threads: 6
interactive_log: false
logging: INFO
resume: null

# sampling
manifold_points: 16384
non_manifold_points: 2048

# data augmentation
transforms:
  voxel_decimation: 0.1
  scaling_intensities: false
  random_rotation_z: true
  random_flip: true

downstream:
  checkpoint_dir: null
  checkpoint_name: null
  batch_size: 8
  num_classes: 17
  max_epochs: 30
  val_interval: 5
  skip_ratio: 1